"""StatusNotifierItem spec glue for the WSLg tray bridge.

Everything in here knows only about the StatusNotifierItem /
StatusNotifierWatcher / dbusmenu specifications and their type gymnastics:
Variant unwrapping, the legacy "com.canical.dbusmenu" spelling, pixmap -> PNG
conversion and D-Bus address resolution.  The bridge logic itself lives in
sni_host.py.
"""

import base64
import io
import logging
import os
from typing import TYPE_CHECKING

from dbus_next import Variant  # pyright: ignore[reportPrivateImportUsage]
from dbus_next.service import (  # pyright: ignore[reportPrivateImportUsage]
    PropertyAccess,  # pyright: ignore[reportPrivateImportUsage]
    ServiceInterface,
    dbus_property,
    method,
    signal,
)
from PIL import Image

if TYPE_CHECKING:
    from sni_host import Bridge

log = logging.getLogger(__name__)

SNI_IFACE = "org.kde.StatusNotifierItem"
PROPS_IFACE = "org.freedesktop.DBus.Properties"
DBUS_IFACE = "org.freedesktop.DBus"
WATCHER_IFACE = "org.kde.StatusNotifierWatcher"

# "com.canical.dbusmenu" (missing the second 'n') is the legacy KDE spelling;
# try every spelling in order until one answers GetLayout.
MENU_IFACES = (
    "com.canonical.dbusmenu",
    "com.ayatana.dbusmenu",
    "com.canical.dbusmenu",
)

# The spec's official name plus the freedesktop.org one.  The bridge owns
# both when it acts as the watcher, so clients probing either name find it
# (Qtile does the same with one service instance per name).
WATCHER_NAMES = (
    "org.kde.StatusNotifierWatcher",
    "org.freedesktop.StatusNotifierWatcher",
)
WATCHER_PATH = "/StatusNotifierWatcher"
ITEM_PATH = "/StatusNotifierItem"
PROTOCOL_VERSION = 1


# dbus type codes for the decorator annotations below (dbus-next reads
# them literally); Pylance would treat "s" as a forward reference.
# pyright: reportInvalidTypeForm=false
class Watcher(ServiceInterface):
    """The StatusNotifierWatcher side of the spec.

    Item/host bookkeeping lives here; pruning happens from
    Bridge.on_bus_message on NameOwnerChanged (as in Qtile's watcher), and
    the bridge learns about lifecycle events through the `on_item_registered`
    / `on_item_unregistered` callbacks.  The D-Bus plumbing (introspection,
    properties, signals) is generated by dbus-next.
    """

    sig_s, sig_as, sig_b, sig_i = "s", "as", "b", "i"

    def __init__(self, bridge: "Bridge"):
        super().__init__(WATCHER_IFACE)
        self.bridge = bridge
        self.items: dict[str, str] = {}  # service -> object path
        self.hosts: set[str] = set()

    def register(self, service: str, path: str = ITEM_PATH) -> None:
        if service not in self.items:
            self.items[service] = path
            self.StatusNotifierItemRegistered(service)
            self.bridge._spawn(self.bridge.on_item_registered(service, path))

    def unregister(self, service: str) -> None:
        if service in self.items:
            del self.items[service]
            self.StatusNotifierItemUnregistered(service)
            self.bridge._spawn(self.bridge.on_item_unregistered(service))

    def register_host(self, service: str) -> None:
        service = str(service)
        if service in self.hosts:
            return
        self.hosts.add(service)
        self.StatusNotifierHostRegistered()  # pyright: ignore[reportCallIssue]
        # replay existing items so the new host sees everything (Qtile does
        # the same)
        for name in self.items:
            self.StatusNotifierItemRegistered(name)

    def unregister_host(self, service: str) -> None:
        if service in self.hosts:
            self.hosts.discard(service)
            self.StatusNotifierHostUnregistered()  # pyright: ignore[reportCallIssue]

    @method()
    def RegisterStatusNotifierItem(self, service: sig_s):
        self.register(str(service))

    @method()
    def RegisterStatusNotifierHost(self, service: sig_s):
        self.register_host(str(service))

    @dbus_property(access=PropertyAccess.READ)
    def RegisteredStatusNotifierItems(self) -> sig_as:
        return list(self.items)

    @dbus_property(access=PropertyAccess.READ)
    def IsStatusNotifierHostRegistered(self) -> sig_b:
        return bool(self.hosts)

    @dbus_property(access=PropertyAccess.READ)
    def ProtocolVersion(self) -> sig_i:
        return 0

    @signal()
    def StatusNotifierItemRegistered(self, service: str) -> sig_s:
        return service

    @signal()
    def StatusNotifierItemUnregistered(self, service: str) -> sig_s:
        return service

    @signal()
    def StatusNotifierHostRegistered(self):
        return None

    @signal()
    def StatusNotifierHostUnregistered(self):
        return None


# --------------------------------------------------------------------- icons
def icon_png(props: dict) -> bytes | None:
    """Best icon of an item as PNG bytes: largest IconPixmap, else a file IconName."""
    best = None  # (w, h, argb data)
    for w, h, data in props.get("IconPixmap") or []:
        if data and w > 0 and h > 0 and (best is None or w * h > best[0] * best[1]):
            best = (w, h, data)
    if best:
        try:
            buf = io.BytesIO()
            Image.frombytes("RGBA", best[:2], bytes(best[2]), "raw", "ARGB").save(
                buf, format="PNG"
            )
            return buf.getvalue()
        except Exception:
            log.exception("failed to convert pixmap")
            return None
    name = props.get("IconName") or ""
    if name.startswith("/") and os.path.isfile(name):
        try:
            with open(name, "rb") as f:
                return f.read()
        except OSError:
            pass
    return None


# --------------------------------------------------------------------- menu
def parse_layout_node(node: tuple | list) -> dict:
    """Convert a com.canonical.dbusmenu GetLayout node into a plain dict."""
    node_id, props, children = node
    p = {k: v.value if isinstance(v, Variant) else v for k, v in props.items()}
    out: dict = {
        "id": int(node_id),
        "label": str(p.get("label") or ""),
        "type": p.get("type") or "standard",
        "enabled": bool(p.get("enabled", True)),
        "visible": bool(p.get("visible", True)),
        "children": [],
    }
    tt = p.get("toggle-type")
    if tt in ("checkmark", "radio"):
        out["checked"] = bool(p.get("toggle-state", 0))
        out["radio"] = tt == "radio"
    ic = p.get("icon-data")
    if isinstance(ic, (bytes, bytearray)) and ic:
        out["icon_png"] = base64.b64encode(bytes(ic)).decode("ascii")
    for ch in children or []:
        inner = ch.value if isinstance(ch, Variant) else ch
        if isinstance(inner, (tuple, list)):
            out["children"].append(parse_layout_node(inner))
    return out


def find_menu_node(nodes: list, label: str) -> dict | None:
    """Depth-first lookup of a menu node by label, recursing into submenus."""
    for node in nodes or []:
        if node.get("label") == label:
            return node
        if (hit := find_menu_node(node.get("children") or [], label)) is not None:
            return hit
    return None


# ------------------------------------------------------------------- entry
def resolve_bus_address() -> str | None:
    addr = os.environ.get("DBUS_SESSION_BUS_ADDRESS")
    if addr:
        return addr
    for addr in (
        "unix:path=/mnt/wslg/runtime-dir/bus",
        f"unix:path=/run/user/{os.getuid()}/bus",
    ):
        if os.path.exists(addr.removeprefix("unix:path=")):
            return addr
    return None
