# Generated by ./update.sh - do not update manually!
# Last updated: 2025-08-04
{
  version = "4.2.1.145";
  amd64_url = "https://ime-sec.gtimg.com/202508040658/ecf44d41933678bf0067446871e4c944/pc/dl/gzindex/1680521603/sogoupinyin_4.2.1.145_amd64.deb";
  arm64_url = "https://ime-sec.gtimg.com/202508040658/5775463a35dfec62cb4dccfef2a3e61e/pc/dl/gzindex/1680521473/sogoupinyin_4.2.1.145_arm64.deb";
  mips64el_url = "https://ime-sec.gtimg.com/202508040658/1f7e51f65638fc9daaaded00593a5b88/pc/dl/gzindex/1680521156/sogoupinyin_4.2.1.145_mips64el.deb";
  loongarch64_url = "https://ime-sec.gtimg.com/202508040658/6d13d8453c235fce04d70c2f0c6b7756/pc/dl/gzindex/1680521801/sogoupinyin_4.2.1.145_loongarch64.deb";
  amd64_hash = "sha256-MRGvF6ar3dgLhWqpwfV5oTfWnz1zXq2TbdtuXwi1nzs=";
  arm64_hash = "sha256-IWNBRmopcqDPkS2yGt2g5hPxWotWI5j8naBRbNr8wa4=";
  mips64el_hash = "sha256-Gu8LG5fe5VEBD5QHkwfHK3Jk1m4mp8SvYeIo+AD7RXI=";
  loongarch64_hash = "sha256-WmFHod9+NPUzgImSch5g8yLWraOPMbiCg/aln4Ng/gQ=";
}
