#! /usr/bin/env nix-shell
#! nix-shell -i bash --pure --keep GITHUB_TOKEN -p nix git curl cacert nix-prefetch-git coreutils

base_url="https://shurufa.sogou.com/linux"

url=()
version=()  # TODO: Currently, there is no version differences between archs. This is reserved for future use.
hash=()
no_hash_urls=$(curl -s $base_url | grep -o "https://[0-9a-z\/\._-]*/sogoupinyin_[0-9\.]*_[0-9a-z]*.deb")

for i in amd64 arm64 mips64el loongarch64
do
    no_hash_url=$(printf "%s\n" "${no_hash_urls[@]}" | grep "$i")
    format_date=$(date +"%Y%m%d%H%M")
    md5_hash=$(printf "44tv2uj7ct7j0gfixf19cs6bdvqdhi$format_date/${no_hash_url#*/*/*/}" | md5sum | awk '{print $1}')
    _url="$(printf $no_hash_url|cut -d'/' -f1-3)/$format_date/$md5_hash/${no_hash_url#*/*/*/}"
    sha256_hash=$(nix-prefetch-url $_url)
    url+=($_url)
    version+=($(printf $no_hash_url | grep -oP "(?<=sogoupinyin_)[0-9\.]*(?=_$i\.deb)"))
    hash+=("$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 $sha256_hash)")
done

cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{
  version = "${version[0]}";
  amd64_url = "${url[0]}";
  arm64_url = "${url[1]}";
  mips64el_url = "${url[2]}";
  loongarch64_url = "${url[3]}";
  amd64_hash = "${hash[0]}";
  arm64_hash = "${hash[1]}";
  mips64el_hash = "${hash[2]}";
  loongarch64_hash = "${hash[3]}";
}
EOF
